spring:
  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:h2:mem:budget}
    username: ${JDBC_DATABASE_USERNAME:sa}
    password: ${JDBC_DATABASE_PASSWORD:1234}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true
  docker:
    compose:
      lifecycle-management: start-only
error:
  handling:
    http-status-in-json-response: true
    exception-logging: NO_LOGGING
    full-stacktrace-http-statuses: 5xx
    log-levels:
      5xx: ERROR
    codes:
      ExerciceCodeUnique: EXERCICE_CODE_UNIQUE
      ExerciceLibelleUnique: EXERCICE_LIBELLE_UNIQUE
      ExerciceDateDebutUnique: EXERCICE_DATE_DEBUT_UNIQUE
      ExerciceDateFinUnique: EXERCICE_DATE_FIN_UNIQUE
      DeviseCodeUnique: DEVISE_CODE_UNIQUE
      DeviseLibelleUnique: DEVISE_LIBELLE_UNIQUE
      DeviseSymboleUnique: DEVISE_SYMBOLE_UNIQUE
      ClasseLibelleUnique: CLASSE_LIBELLE_UNIQUE
      PlanComptableLibelleUnique: PLAN_COMPTABLE_LIBELLE_UNIQUE
      PlanComptableNumeroUnique: PLAN_COMPTABLE_NUMERO_UNIQUE
      ProjetCodeUnique: PROJET_CODE_UNIQUE
      ProjetLibelleUnique: PROJET_LIBELLE_UNIQUE
      CategorieCodeUnique: CATEGORIE_CODE_UNIQUE
      CategorieLibelleUnique: CATEGORIE_LIBELLE_UNIQUE
      ActiviteCodeUnique: ACTIVITE_CODE_UNIQUE
      ActiviteLibelleUnique: ACTIVITE_LIBELLE_UNIQUE
      TypSourceFinancementLibelleUnique: TYP_SOURCE_FINANCEMENT_LIBELLE_UNIQUE
      SourceFinacementCodeUnique: SOURCE_FINACEMENT_CODE_UNIQUE
      SourceFinacementLibelleUnique: SOURCE_FINACEMENT_LIBELLE_UNIQUE
springdoc:
  pathsToMatch: /, /api/**
server:
  servlet:
    context-path: /budget/v1
